language: "zh"

pipeline:
- name: "tokenizer_jieba"
- name: "intent_entity_featurizer_regex"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_featurizer_count_vectors"
  "token_pattern": '(?u)\b\w+\b'    #\b:匹配一个单词边界,\w:匹配字母数字,+:匹配一个或多个
- name: "intent_classifier_tensorflow_embedding"

policies:
  - name: KerasPolicy
    epochs: 150
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy